title: OS Lab 4 - Making Progress!
author: Muhammad Bilal Afzal
email: mafzal.bscs18seecs@seecs.edu.pk
description: > # this means to ignore newlines until "baseurl:"
  Hi, I'm Bilal Afzal, a fullstack Web3 Developer. I'm currently assisting the team at Robor systems in building an NFT marketplace, Tokapi!

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  bilalafzal01 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
